### ISSUE TITLE
Production minification errors when using useraccounts:foundation

### ISSUE THREAD

**Issue by aaronlake** [meteor-useraccounts/foundation#3]
When running the following packages:
```
meteor-platform
orionjs:core
orionjs:styles
useraccounts:core
accounts-password
matthew:foundation5-sass
fourseven:scss
orionjs:froala-editor
mrt:moment
zimme:iron-router-active
orionjs:bootstrap
orionjs:filesystem
meteorhacks:sikka
```

I receive the following errors in the console when deployed to production using `mup deploy` or localy using `--production`. 

```
Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined
Uncaught ReferenceError: UI is not defined
Uncaught ReferenceError: Spacebars is not defined
```

Removing useraccounts:foundation resolves the issue.

Gist of `versions`: https://gist.github.com/aaronlake/26c5a0c10c9c50a62ddc

**Comment by splendido** [comment]
hey @aaronlake, sorry for the late reply!

why do [you have also](https://gist.github.com/aaronlake/26c5a0c10c9c50a62ddc#file-gistfile1-txt-L91) `useraccounts:bootstrap`? Are you trying to create a new styling for `orionjs`?
Lets try to get rid of it!

Btw, from the errors you're reporting it's hard to say what the problem is...
